### ISSUE TITLE
Unable to use custom arguments. Only the first caracter is save in variable

### ISSUE THREAD

**Issue by dbrillon** [VSoftTechnologies/FinalBuilder-VSO#5]
I tried to use the custom arguments but when I assign a variable to the argument only the first caracter is transfered.

ex: 
A set this in VSTS under the Custom Arguments
This is a test

In FinalBuilder a set a variable of type string "BuildVersionSelector" and set it to the "Custom Argument 1" parameters in the Custom Arguments section of the "Get TEAM Foundation Build Parameters" Action in FinalBuilder.

I save the variable in a ini file and the result is
[FBVariables]
BuildVersionSelector=T

**Comment by dbrillon** [comment]
This is only true if a set only one arguments.  If I put more than one line then the parameters works.

ex:
This will not work:
This is a test 4_25

This will work:
This is a test 4_25
This is arg 2
This is arg 3

**Comment by staticcat** [comment]
I have task so that it correctly extracts the first argument when it is the only argument. The new task version is 1.0.31. 

https://marketplace.visualstudio.com/items?itemName=vsoft.finalbuilder-extension
